spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: spems-backend
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

spems:
  jwt:
    secret: ${JWT_SECRET:9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b}
    expiration-ms: 900000 # 15 mins
    refresh-expiration-ms: 604800000 # 7 days
  storage:
    local-directory: ${STORAGE_LOCAL_DIRECTORY:./uploads}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
